// A '.tsx' file enables JSX support in the TypeScript compiler, 
// for more information see the following page on the TypeScript wiki:
// https://github.com/Microsoft/TypeScript/wiki/JSX
import * as React from "react";
import * as ReactDOM from "react-dom";
ReactDOM.render(React.createElement("div", { id: "page-top" },
    React.createElement("nav", { class: "navbar navbar-expand-lg navbar-light fixed-top", id: "mainNav" },
        React.createElement("div", { class: "container" },
            React.createElement("a", { class: "navbar-brand js-scroll-trigger", href: "#page-top" }, "Antykhimera"),
            React.createElement("button", { class: "navbar-toggler navbar-toggler-right", type: "button", "data-toggle": "collapse", "data-target": "#navbarResponsive", "aria-controls": "navbarResponsive", "aria-expanded": "false", "aria-label": "Toggle navigation" },
                "Menu",
                React.createElement("i", { class: "fas fa-bars" })),
            React.createElement("div", { class: "collapse navbar-collapse", id: "navbarResponsive" },
                React.createElement("ul", { class: "navbar-nav ml-auto" },
                    React.createElement("li", { class: "nav-item" },
                        React.createElement("a", { class: "nav-link js-scroll-trigger", href: "#about" }, "Pr\u00E9sentation")),
                    React.createElement("li", { class: "nav-item" },
                        React.createElement("a", { class: "nav-link js-scroll-trigger", href: "#projects" }, "Activit\u00E9")),
                    React.createElement("li", { class: "nav-item" },
                        React.createElement("a", { class: "nav-link js-scroll-trigger", href: "#Galerie" }, "Galerie")),
                    React.createElement("li", { class: "nav-item" },
                        React.createElement("a", { class: "nav-link js-scroll-trigger", href: "#contact" }, "Contact")))))),
    React.createElement("header", { class: "masthead" },
        React.createElement("div", { class: "container d-flex h-100 align-items-center" },
            React.createElement("div", { class: "mx-auto text-center" },
                React.createElement("h1", { class: "mx-auto my-0 text-uppercase" }, "Antykhimera"),
                React.createElement("h2", { class: "text-white-50 mx-auto mt-2 mb-5" }, "Association de Trollball et Jeux de R\u00F4le Grandeur Nature"),
                React.createElement("a", { href: "#about", class: "btn btn-primary js-scroll-trigger" }, "Pr\u00E9sentation")))),
    React.createElement("section", { id: "about", class: "about-section text-center" },
        React.createElement("div", { class: "container" },
            React.createElement("div", { class: "row" },
                React.createElement("div", { class: "col-lg-8 mx-auto" },
                    React.createElement("h2", { class: "text-white mb-4" }, "Pr\u00E9sentation"),
                    React.createElement("p", { class: "text-white-50" },
                        " L\u2019Antykhimera est une association promouvant le jeu de r\u00F4le Grandeur Nature et le Trollball, cr\u00E9\u00E9e en novembre 2013, par une bande d\u2019amis souhaitant partager leurs loisirs. Aujourd\u2019hui, elle compte une trentaine de membres et pratique ses activit\u00E9s sur toute la r\u00E9gion lyonnaise, et m\u00EAme plus loin !",
                        React.createElement("br", null),
                        React.createElement("br", null),
                        "Nous sommes une petite troupe de passionn\u00E9s qui se r\u00E9unit tous les dimanches et les mercredis soir, sur la belle ville de Lyon, arm\u00E9e d\u2019\u00E9p\u00E9es en mousse et de lourds boucliers, d\u2019arcs, de dagues de lancer et autre jambon en mousse pour s'entrain\u00E9 \u00E0 l'escrime ludique et au trollbal. Nous proposons aussi des activit\u00E9s au grand public lors de convention ou de f\u00EAtes m\u00E9di\u00E9vales-fantastiques, tels que le festival Yggdrasil a Lyon.",
                        React.createElement("br", null),
                        React.createElement("br", null),
                        "L\u2019association donne \u00E0 tous ceux qui le souhaitent, la possibilit\u00E9 de cr\u00E9er, que ce soit des animations, des entra\u00EEnements voir m\u00EAme des GNs !",
                        React.createElement("br", null),
                        "Et ses portes vous sont ouvertes !",
                        React.createElement("br", null),
                        "L\u2019Antykhimera, vaincra !",
                        React.createElement("br", null)))),
            React.createElement("img", { src: "img/ipad.png", class: "img-fluid", alt: "" }))),
    React.createElement("section", { id: "projects", class: "projects-section bg-light" },
        React.createElement("div", { class: "container" },
            React.createElement("div", { class: "row align-items-center no-gutters mb-4 mb-lg-5" },
                React.createElement("div", { class: "col-xl-8 col-lg-7" },
                    React.createElement("img", { class: "img-fluid mb-3 mb-lg-0", src: "img/bg-masthead.jpg", alt: "" })),
                React.createElement("div", { class: "col-xl-4 col-lg-5" },
                    React.createElement("div", { class: "featured-text text-center text-lg-left" },
                        React.createElement("h4", null, "Escrime ludique"),
                        React.createElement("p", { class: "text-black-50 mb-0" }, " C'est une activit\u00E9 sportive utilis\u00E9e notamment en gn, permettant de combattre avec des armes en mousse de mani\u00E8re s\u00E9curis\u00E9."),
                        " ",
                        React.createElement("p", { class: "text-black-50 mb-0" },
                            " ",
                            React.createElement("i", null, "Des r\u00E9glementations strictes sont tout de fois pr\u00E9sente comme l'interdiction de l'estoc et des coups trop fort ou aux parties sensibles."))))),
            React.createElement("div", { class: "row justify-content-center no-gutters mb-5 mb-lg-0" },
                React.createElement("div", { class: "col-lg-6" },
                    React.createElement("img", { class: "img-fluid", src: "img/demo-image-01.jpg", alt: "" })),
                React.createElement("div", { class: "col-lg-6" },
                    React.createElement("div", { class: "bg-black text-center h-100 project" },
                        React.createElement("div", { class: "d-flex h-100" },
                            React.createElement("div", { class: "project-text w-100 my-auto text-center text-lg-left" },
                                React.createElement("h4", { class: "text-white" }, "TrollBall"),
                                React.createElement("p", { class: "mb-0 text-white-50" }, "Sport m\u00EAlant escrime ludique et rugby. Il y a deux \u00E9quipes arm\u00E9es et une balle au centre, le but est de mettre la balle de l'autre c\u00F4t\u00E9 des lignes adverses ou d\u2019\u00E9liminer l'autre \u00E9quipe."),
                                React.createElement("p", { class: "mb-0 text-white-50" }, " Pour varier le plaisir nous mettons en place des manches sp\u00E9ciales avec des contraintes vari\u00E9es pour plus de fun! "),
                                React.createElement("hr", { class: "d-none d-lg-block mb-0 ml-0" })))))),
            React.createElement("div", { class: "row justify-content-center no-gutters" },
                React.createElement("div", { class: "col-lg-6" },
                    React.createElement("img", { class: "img-fluid", src: "img/demo-image-02.jpg", alt: "" })),
                React.createElement("div", { class: "col-lg-6 order-lg-first" },
                    React.createElement("div", { class: "bg-black text-center h-100 project" },
                        React.createElement("div", { class: "d-flex h-100" },
                            React.createElement("div", { class: "project-text w-100 my-auto text-center text-lg-right" },
                                React.createElement("h4", { class: "text-white" }, "GN"),
                                React.createElement("p", { class: "mb-0 text-white-50" }, "\u00C9volution du JdR papier o\u00F9 les joueurs incarnent physiquement un personnage dans un univers fictif. Ils interpr\u00E8tent leur personnage avec diverses interactions et actions physiques, d'apr\u00E8s des r\u00E8gles de jeu et l'arbitrage d'organisateurs. "),
                                " ",
                                React.createElement("p", { class: "text-white-50 mb-0" }, " Le jeu peut se d\u00E9rouler dans different univers autant medieval-fantastisque que futuriste ou post-apo."),
                                " ",
                                React.createElement("p", { class: "text-white-50 mb-0" },
                                    React.createElement("i", null, " Un objectif de l'association sur le long terme est d'organiser son propre gn.")),
                                React.createElement("hr", { class: "d-none d-lg-block mb-0 mr-0" })))))),
            React.createElement("div", { class: "row justify-content-center no-gutters mb-5 mb-lg-0" },
                React.createElement("div", { class: "col-lg-6" },
                    React.createElement("img", { class: "img-fluid", src: "img/demo-image-01.jpg", alt: "" })),
                React.createElement("div", { class: "col-lg-6" },
                    React.createElement("div", { class: "bg-black text-center h-100 project" },
                        React.createElement("div", { class: "d-flex h-100" },
                            React.createElement("div", { class: "project-text w-100 my-auto text-center text-lg-left" },
                                React.createElement("h4", { class: "text-white" }, "Craft"),
                                React.createElement("p", { class: "mb-0 text-white-50" }, "Que \u00E7a soit le travail du cuir, du m\u00E9tal, du tissu ou du bois, certains Gnistes se sont sp\u00E9cialis\u00E9s dans la fabrication de certains objets pour des besoins personnels et aussi pour le partager aux autres."),
                                React.createElement("p", { class: "mb-0 text-white-50" }, " R\u00E9guli\u00E8rement, nos membres se r\u00E9unissent lors d'atelier o\u00F9 nous travaillons sur des projets d'artisanats pour le groupe comme la fabrication d'\u00E9l\u00E9ments pour notre campement, d'arme ou costumes."),
                                React.createElement("hr", { class: "d-none d-lg-block mb-0 ml-0" })))))),
            React.createElement("div", { class: "row justify-content-center no-gutters" },
                React.createElement("div", { class: "col-lg-6" },
                    React.createElement("img", { class: "img-fluid", src: "img/demo-image-02.jpg", alt: "" })),
                React.createElement("div", { class: "col-lg-6 order-lg-first" },
                    React.createElement("div", { class: "bg-black text-center h-100 project" },
                        React.createElement("div", { class: "d-flex h-100" },
                            React.createElement("div", { class: "project-text w-100 my-auto text-center text-lg-right" },
                                React.createElement("h4", { class: "text-white" }, "Evenement"),
                                React.createElement("p", { class: "mb-0 text-white-50" }, "Pour faire d\u00E9couvrir nos activit\u00E9s, l'association participe \u00E0 de nombreux \u00E9v\u00E9nements tout au long de l'ann\u00E9e dans la r\u00E9gion lyonnaise."),
                                React.createElement("hr", { class: "d-none d-lg-block mb-0 mr-0" })))))))),
    React.createElement("section", { id: "Galerie", class: "signup-section" },
        React.createElement("div", { class: "container" },
            React.createElement("div", { class: "row" },
                React.createElement("div", { class: "col-md-10 col-lg-8 mx-auto text-center" },
                    React.createElement("i", { class: "far fa-paper-plane fa-2x mb-2 text-white" }),
                    React.createElement("h2", { class: "text-white mb-5" }, "Galerie"))))),
    React.createElement("section", { class: "contact-section bg-black", id: "contact" },
        React.createElement("div", { class: "container" },
            React.createElement("div", { class: "row justify-content-center no-gutters mb-5 mb-lg-0" },
                React.createElement("div", { class: "col-lg-6" },
                    React.createElement("div", { id: "google-map", "data-latitude": "40.713732", "data-longitude": "-74.0092704" })),
                React.createElement("div", { class: "col-lg-6" },
                    React.createElement("div", { class: "bg-black text-center h-100 project" },
                        React.createElement("div", { class: "d-flex h-100" },
                            React.createElement("div", { class: "project-text w-100 my-auto text-center text-lg-left" },
                                React.createElement("h4", { class: "text-white" }, "Entrainement"),
                                React.createElement("p", { class: "mb-0 text-white-50" }, "Nous nous entrainons \u00E0 la doua (voir carte-ci-contre) le samedi \u00E0 partir de 14h30 et le mercredi \u00E0 19h30 uniquement pendant l'heure d'\u00E9t\u00E9. "),
                                React.createElement("hr", { class: "d-none d-lg-block mb-0 ml-0" })))))),
            React.createElement("div", { class: "row" },
                React.createElement("div", { class: "col-md-4 mb-3 mb-md-0" },
                    React.createElement("div", { class: "card py-4 h-100" },
                        React.createElement("div", { class: "card-body text-center" },
                            React.createElement("i", { class: "fas fa-map-marked-alt text-primary mb-2" }),
                            React.createElement("h4", { class: "text-uppercase m-0" }, "Adresse"),
                            React.createElement("hr", { class: "my-4" }),
                            React.createElement("div", { class: "small text-black-50" }, "71b Avenue Paul Santy 69008 Lyon")))),
                React.createElement("div", { class: "col-md-4 mb-3 mb-md-0" },
                    React.createElement("div", { class: "card py-4 h-100" },
                        React.createElement("div", { class: "card-body text-center" },
                            React.createElement("i", { class: "fas fa-envelope text-primary mb-2" }),
                            React.createElement("h4", { class: "text-uppercase m-0" }, "Email"),
                            React.createElement("hr", { class: "my-4" }),
                            React.createElement("div", { class: "small text-black-50" },
                                React.createElement("a", { href: "#" }, "antykhimera@hotmail.fr"))))),
                React.createElement("div", { class: "col-md-4 mb-3 mb-md-0" },
                    React.createElement("div", { class: "card py-4 h-100" },
                        React.createElement("div", { class: "card-body text-center" },
                            React.createElement("i", { class: "fas fa-mobile-alt text-primary mb-2" }),
                            React.createElement("h4", { class: "text-uppercase m-0" }, "Telephone"),
                            React.createElement("hr", { class: "my-4" }),
                            React.createElement("div", { class: "small text-black-50" }, "07 81 78 71 24"))))),
            React.createElement("div", { class: "social d-flex justify-content-center" },
                React.createElement("a", { href: "https://www.facebook.com/antykhimera/", class: "mx-2" },
                    React.createElement("i", { class: "fab fa-facebook-f" }))))),
    React.createElement("footer", { class: "bg-black small text-center text-white-50" },
        React.createElement("div", { class: "container" }, "Copyright \u00A9 Your Website 2018"))), document.getElementById("content"));
